# Generated by Django 5.1.2 on 2024-10-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auction_status_auctionitem_status_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='item',
        ),
        migrations.AddField(
            model_name='auction',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction',
            name='image',
            field=models.ImageField(default=1, upload_to='auction_items/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AuctionItem',
        ),
    ]
