# Generated by Django 5.1.2 on 2024-10-30 11:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_remove_auction_item_auction_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='auctions', to=settings.AUTH_USER_MODEL),
        ),
    ]
