# Generated by Django 5.1.2 on 2024-12-12 08:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_remove_auction_users_auction_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='user',
        ),
        migrations.AddField(
            model_name='auction',
            name='users',
            field=models.ManyToManyField(related_name='auctions', to=settings.AUTH_USER_MODEL),
        ),
    ]
